// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SL_StockTrade.Models;

namespace SL_StockTrade.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201211074424_SeedSellerdatasample2")]
    partial class SeedSellerdatasample2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SL_StockTrade.Models.Seller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<string>("BannerImg");

                    b.Property<string>("BusinessName")
                        .IsRequired();

                    b.Property<int>("Country");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(128);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("InChargePerson")
                        .IsRequired();

                    b.Property<string>("Location")
                        .IsRequired();

                    b.Property<string>("Mobile");

                    b.Property<string>("Password");

                    b.Property<double>("PlatformCharge");

                    b.Property<string>("ProfileImg");

                    b.Property<string>("RegistredDate")
                        .IsRequired();

                    b.Property<int>("SalesGoodType");

                    b.Property<string>("Telephone")
                        .IsRequired();

                    b.Property<string>("Username");

                    b.Property<string>("Web");

                    b.HasKey("Id");

                    b.ToTable("Sellers");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Address = "Downtown center",
                            BannerImg = "img",
                            BusinessName = "Masala Shop",
                            Country = 1,
                            Description = "some textsome textsome textsome textsome textsome text",
                            Email = "delushaan@outlook.com",
                            InChargePerson = "Ruchiragna",
                            Location = "Downtown",
                            Mobile = "0000000000",
                            PlatformCharge = 5.7999999999999998,
                            ProfileImg = "prof",
                            RegistredDate = "12/11/2020 12:00:00 AM",
                            SalesGoodType = 1,
                            Telephone = "1111111111",
                            Web = "www.google.com"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Downtown center",
                            BannerImg = "img",
                            BusinessName = "Ruchiragna Masala Shop",
                            Country = 1,
                            Description = "some textsome textsome textsome textsome textsome text",
                            Email = "delushaan@outlook.com",
                            InChargePerson = "Ruchiragna",
                            Location = "Downtown",
                            Mobile = "0000000000",
                            PlatformCharge = 5.7999999999999998,
                            ProfileImg = "prof",
                            RegistredDate = "12/11/2020 12:00:00 AM",
                            SalesGoodType = 1,
                            Telephone = "1111111111",
                            Web = "www.google.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
